# Make sure to set your other required secrets first.
#
# Use this file by running `kubectl create -f <this-file>`

###
# This creates a service account so we can get an auth token for the janitor.
###
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: ecr-auto-deploy-account

---
###
# This Creates a secret using our service account so we can mount it to the Application.
###
apiVersion: v1
kind: Secret
metadata:
  name: ecr-auto-deploy-access-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: "ecr-auto-deploy-account"
type: kubernetes.io/service-account-token

---
###
# This is our Auto deploy server Pod, currently we dont support HA deployments so we only have one.
###
apiVersion: v1
kind: Pod
metadata:
  name: ecr-auto-deploy
  namespace: kube-system
  labels:
    app: ecr-auto-deploy
    roles: auto-deploy
spec:
  containers:
    -
      name: ecr-auto-deploy
      image: "andr3whur5t/kubernetes-ecr-autodeploy:v0.2"
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 0.1
          memory: 125Mi
        requests:
          cpu: 0.01
          memory: 75Mi
      env:
        - name: "NODE_ENV"
          value: "production"
        - name: "PERIOD_TO_POLL_SECONDS"
          value: "60"

        # Set the bucket name you put the config file here
        - name: "S3_DEPLOYMENT_BUCKET"
          value: "YOUR_BUCKET_NAME"

        # Set this to the Path + Name of the config file
        - name: "S3_DEPLOYMENT_KEY"
          value: "auto-deploy-spec.json"

        ## Use this to change your AWS S3 region
        - name: "AWS_S3_REGION"
          value: "us-east-1"

        ## Use this to change your AWS ERC region
        - name: "AWS_ERC_REGION"
          value: "us-east-1"

        # Use this to bypass ssl validation; Not recomended, but can be used to debug issues.
        - name: "KUBE_STRICT_SSL"
          value: "true"

        # Need AWS to talk to ECR and S3, add your credentials as secrets
        - name: "AWS_ACCESS_KEY_ID"
          valueFrom:
            secretKeyRef:
              name: "ecr-auto-deploy-iam"
              key: "id"
        - name: "AWS_SECRET_ACCESS_KEY"
          valueFrom:
            secretKeyRef:
              name: "ecr-auto-deploy-iam"
              key: "secret"

        # This gives the Pod access to the service account so we can deploy changes.
        - name: "KUBE_AUTH_TOKEN"
          valueFrom:
            secretKeyRef:
              name: "ecr-auto-deploy-access-token"
              key: "token"
